[package]
name = "hroguelike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "maingame"
path = "src/main_gui.rs"

[dependencies]
macroquad="~0.4"
glam = "~0.24"
#specs = { version = "~0.20.0", features = ["specs-derive"] }
num = "~0.4"
num-derive = "~0.4"
num-traits = "~0.2"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
legion = { version = "~0.4", features = [] }
[target.'cfg(target_family = "wasm")'.dependencies]
legion = { version = "~0.4", default-features = false, features = ["wasm-bindgen"] }

# rustup target install wasm32-unknown-unknown
# cargo install wasm-server-runner
[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
# cargo install wasm-bindgen-cli
# cargo build --release --target wasm32-unknown-unknown
# wasm-bindgen --out-dir ./web/ --target web ./target/