[package]
name = "hroguelike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "maingame"
path = "src/main_gui.rs"

[dependencies]
macroquad="~0.4.4"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
legion = { version = "~0.4.0", features = [] }

[target.'cfg(target_family = "wasm")'.dependencies]
legion = { version = "~0.4.0", default-features = false, features = ["wasm-bindgen"] }

# rustup target install wasm32-unknown-unknown
# cargo install wasm-server-runner
[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
# cargo install wasm-bindgen-cli
# cargo build --release --target wasm32-unknown-unknown
# wasm-bindgen --out-dir ./web/ --target web ./target/